name: Bug 报告
description: 报告一个出现的问题
title: "[Bug] 简要描述问题"
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么
      description: 描述预期行为与实际结果，附带错误信息（如有）
      placeholder: |
        预期行为：...
        实际结果：...
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: 复现步骤
      description: 请提供最小复现步骤，便于快速定位
      placeholder: |
        1. 打开 ...
        2. 点击 ...
        3. 看到错误 ...
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: 受影响页面或链接
      placeholder: 例如 https://<username>.github.io/<repo>/
  - type: dropdown
    id: browsers
    attributes:
      label: 浏览器
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
        - 其他
  - type: checkboxes
    id: checklist
    attributes:
      label: 自检
      options:
        - label: 已清除缓存或隐身模式下重试
        - label: 已拉取最新 main 并本地复现
        - label: 已在不同浏览器上验证
  - type: textarea
    id: extra
    attributes:
      label: 其他上下文 / 截图


